package vista;

import clases.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.DAO;

/**
 *
 * @author xDoble_Jx
 */
public class PInicio extends javax.swing.JPanel {

    private VMain vMain;
    private DAO dao;

    /**
     * Creates new form PInicio
     */
    public PInicio(VMain vMain, DAO dao) {
        this.vMain = vMain;
        this.dao = dao;

        initComponents();
        setBackground(new Color(0, 0, 0, 0));
    }

    private void iniciarSesion() {
        Usuario usu = dao.iniciarSesion(txtUsuario.getText(), txtContrasenia.getText());

        if (usu != null) {
            vMain.setOpacity(0);
            VPrincipal vPrincipal = new VPrincipal(vMain, true, dao, usu);
            vPrincipal.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "El usuario y contraseña no coinciden", "Error", 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new utilidades.LookVentana.RoundPanel();
        pnlContenido = new utilidades.LookVentana.RoundPanel();
        imgLogo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        spUsuario = new javax.swing.JSeparator();
        txtContrasenia = new javax.swing.JPasswordField();
        spContrasenia = new javax.swing.JSeparator();
        btnIniciar = new utilidades.LookVentana.Button();

        setBackground(new java.awt.Color(43, 45, 47));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(512, 530));

        roundPanel1.setBackground(new java.awt.Color(21, 21, 21));

        pnlContenido.setBackground(new java.awt.Color(49, 51, 53));
        pnlContenido.setPreferredSize(new java.awt.Dimension(512, 530));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/pantalla/LogoGrande.png"))); // NOI18N

        lblLogo.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(227, 227, 227));
        lblLogo.setText("Spotify");

        txtUsuario.setBackground(pnlContenido.getBackground());
        txtUsuario.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(227, 227, 227));
        txtUsuario.setText("Nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });

        spUsuario.setForeground(new java.awt.Color(227, 227, 227));

        txtContrasenia.setBackground(pnlContenido.getBackground());
        txtContrasenia.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtContrasenia.setForeground(new java.awt.Color(227, 227, 227));
        txtContrasenia.setText("Contraseña");
        txtContrasenia.setBorder(null);
        txtContrasenia.setEchoChar((char) 0);
        txtContrasenia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContraseniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContraseniaFocusLost(evt);
            }
        });

        spContrasenia.setForeground(new java.awt.Color(227, 227, 227));

        btnIniciar.setBackground(new java.awt.Color(227, 227, 227));
        btnIniciar.setForeground(new java.awt.Color(51, 51, 51));
        btnIniciar.setText("Iniciar Sesion");
        btnIniciar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenidoLayout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsuario)
                    .addComponent(txtContrasenia)
                    .addComponent(spUsuario)
                    .addComponent(spContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(imgLogo)
                        .addGap(18, 18, 18)
                        .addComponent(lblLogo))
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgLogo)
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblLogo)))
                .addGap(58, 58, 58)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(spUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(spContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if (txtUsuario.getText().equalsIgnoreCase("Nombre de usuario")) {
            txtUsuario.setText("");
        }
        spUsuario.setForeground(new Color(0, 153, 255));
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if (txtUsuario.getText().isBlank()) {
            txtUsuario.setText("Nombre de usuario");
        }
        spUsuario.setForeground(new Color(227, 227, 227));
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtContraseniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseniaFocusGained
        if (txtContrasenia.getText().equalsIgnoreCase("Contraseña")) {
            txtContrasenia.setText("");
            txtContrasenia.setEchoChar('*');
        }
        spContrasenia.setForeground(new Color(0, 153, 255));
    }//GEN-LAST:event_txtContraseniaFocusGained

    private void txtContraseniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseniaFocusLost
        if (txtContrasenia.getText().isBlank()) {
            txtContrasenia.setText("Contraseña");
            txtContrasenia.setEchoChar((char) 0);
        }

        spContrasenia.setForeground(new Color(227, 227, 227));
    }//GEN-LAST:event_txtContraseniaFocusLost

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        iniciarSesion();
    }//GEN-LAST:event_btnIniciarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilidades.LookVentana.Button btnIniciar;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lblLogo;
    private utilidades.LookVentana.RoundPanel pnlContenido;
    private utilidades.LookVentana.RoundPanel roundPanel1;
    private javax.swing.JSeparator spContrasenia;
    private javax.swing.JSeparator spUsuario;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
