package vista;

import clases.Usuario;
import java.awt.Color;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.DAO;

/**
 *
 * @author xDoble_Jx
 */
public class PRegistrar extends javax.swing.JPanel {

    private VMain vMain;
    private DAO dao;

    /**
     * Creates new form PRegistrar
     */
    public PRegistrar(VMain vMain, DAO dao) {
        this.vMain = vMain;
        this.dao = dao;

        initComponents();
        setBackground(new Color(0, 0, 0, 0));
    }

    private void comprobarDatos() {
        String mensaje = "";

        if (txtUsuario.getText().equalsIgnoreCase("Nombre de usuario")) {
            mensaje += "Por favor introduce un usuario\n";
            spUsuario.setForeground(new Color(153, 0, 0));
            txtUsuario.setForeground(new Color(153, 0, 0));

        } else if (txtUsuario.getText().length() > 25) {
            mensaje += "El usuario no puede tener mas de 25 caracteres\n";
            spUsuario.setForeground(new Color(153, 0, 0));
            txtUsuario.setForeground(new Color(153, 0, 0));

        } else {
            spUsuario.setForeground(new Color(51, 153, 0));
            txtUsuario.setForeground(new Color(51, 153, 0));
        }

        if (txtContrasenia.getText().equalsIgnoreCase("Contraseña")) {
            mensaje += "Por favor introduce una contraseña\n";
            spContrasenia.setForeground(new Color(153, 0, 0));
            txtContrasenia.setForeground(new Color(153, 0, 0));

        } else if (txtContrasenia.getText().length() > 25) {
            mensaje += "La contraseña no puede tener mas de 25 caracteres\n";
            spContrasenia.setForeground(new Color(153, 0, 0));
            txtContrasenia.setForeground(new Color(153, 0, 0));

        } else {
            spContrasenia.setForeground(new Color(51, 153, 0));
            txtContrasenia.setForeground(new Color(51, 153, 0));
        }

        if (txtCorreo.getText().equalsIgnoreCase("Correo electronico")) {
            mensaje += "Introduce un correo\n";
            spCorreo.setForeground(new Color(153, 0, 0));
            txtCorreo.setForeground(new Color(153, 0, 0));

        } else if (txtCorreo.getText().length() > 50) {
            mensaje += "El correo no puede tener mas de 50 caracteres\n";
            spCorreo.setForeground(new Color(153, 0, 0));
            txtCorreo.setForeground(new Color(153, 0, 0));

        } else if (!txtCorreo.getText().matches("^[A-Za-z0-9+_.-]+@gmail\\.com$")) {
            mensaje += "El correo no es valido\n";
            spCorreo.setForeground(new Color(153, 0, 0));
            txtCorreo.setForeground(new Color(153, 0, 0));

        } else {
            spCorreo.setForeground(new Color(51, 153, 0));
            txtCorreo.setForeground(new Color(51, 153, 0));

        }

        if (txtFecha_nac.getText().equalsIgnoreCase("Fecha de nacimiento")) {
            mensaje += "Por favor introduce una fecha de nacimiento\n";
            spFecha_nac.setForeground(new Color(153, 0, 0));
            txtFecha_nac.setForeground(new Color(153, 0, 0));

        } else {
            spFecha_nac.setForeground(new Color(51, 153, 0));
            txtFecha_nac.setForeground(new Color(51, 153, 0));
        }

        if (mensaje == "") {
            registrar();
            System.out.println("vista.PRegistrar.comprobarDatos()");
        } else {
            JOptionPane.showMessageDialog(this, mensaje, "Error", 2);
        }
    }

    public void registrar() {
        Usuario usu = new Usuario();

        usu.setId_usuario(dao.calcularIdUsuario());
        usu.setNombre(txtUsuario.getText());
        usu.setContrasenia(txtContrasenia.getText());
        usu.setCorreo(txtCorreo.getText());
        usu.setFecha_nac(LocalDate.parse(txtFecha_nac.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd")));

        dao.registrarUsuario(usu);
        JOptionPane.showMessageDialog(this, "Usuario registrado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new utilidades.LookVentana.RoundPanel();
        imgLogo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        spUsuario = new javax.swing.JSeparator();
        txtContrasenia = new javax.swing.JPasswordField();
        spContrasenia = new javax.swing.JSeparator();
        btnRegistrar = new utilidades.LookVentana.Button();
        txtCorreo = new javax.swing.JTextField();
        spCorreo = new javax.swing.JSeparator();
        txtFecha_nac = new javax.swing.JTextField();
        spFecha_nac = new javax.swing.JSeparator();

        pnlContenido.setBackground(new java.awt.Color(49, 51, 53));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/pantalla/LogoGrande.png"))); // NOI18N

        lblLogo.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(227, 227, 227));
        lblLogo.setText("Spotify");

        txtUsuario.setBackground(pnlContenido.getBackground());
        txtUsuario.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(227, 227, 227));
        txtUsuario.setText("Nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });

        spUsuario.setForeground(new java.awt.Color(227, 227, 227));

        txtContrasenia.setBackground(pnlContenido.getBackground());
        txtContrasenia.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtContrasenia.setForeground(new java.awt.Color(227, 227, 227));
        txtContrasenia.setText("Contraseña");
        txtContrasenia.setBorder(null);
        txtContrasenia.setEchoChar((char) 0);
        txtContrasenia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContraseniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContraseniaFocusLost(evt);
            }
        });

        spContrasenia.setForeground(new java.awt.Color(227, 227, 227));

        btnRegistrar.setBackground(new java.awt.Color(227, 227, 227));
        btnRegistrar.setForeground(new java.awt.Color(51, 51, 51));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtCorreo.setBackground(pnlContenido.getBackground());
        txtCorreo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(227, 227, 227));
        txtCorreo.setText("Correo electronico");
        txtCorreo.setBorder(null);
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });

        spCorreo.setForeground(new java.awt.Color(227, 227, 227));

        txtFecha_nac.setBackground(pnlContenido.getBackground());
        txtFecha_nac.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtFecha_nac.setForeground(new java.awt.Color(227, 227, 227));
        txtFecha_nac.setText("Fecha de nacimiento");
        txtFecha_nac.setBorder(null);
        txtFecha_nac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFecha_nacFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFecha_nacFocusLost(evt);
            }
        });

        spFecha_nac.setForeground(new java.awt.Color(227, 227, 227));

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(imgLogo)
                .addGap(18, 18, 18)
                .addComponent(lblLogo)
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenidoLayout.createSequentialGroup()
                        .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFecha_nac)
                                .addComponent(spFecha_nac, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCorreo)
                                .addComponent(spCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsuario)
                                .addComponent(spUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtContrasenia)
                                .addComponent(spContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenidoLayout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))))
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgLogo)
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblLogo)))
                .addGap(13, 13, 13)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(spUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(spContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(spCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFecha_nac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(spFecha_nac, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if (txtUsuario.getText().equalsIgnoreCase("Nombre de usuario")) {
            txtUsuario.setText("");
        }
        spUsuario.setForeground(new Color(0, 153, 255));
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if (txtUsuario.getText().isBlank()) {
            txtUsuario.setText("Nombre de usuario");
        }
        spUsuario.setForeground(new Color(227, 227, 227));
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtContraseniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseniaFocusGained
        if (txtContrasenia.getText().equalsIgnoreCase("Contraseña")) {
            txtContrasenia.setText("");
            txtContrasenia.setEchoChar('*');
        }
        spContrasenia.setForeground(new Color(0, 153, 255));
    }//GEN-LAST:event_txtContraseniaFocusGained

    private void txtContraseniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseniaFocusLost
        if (txtContrasenia.getText().isBlank()) {
            txtContrasenia.setText("Contraseña");
            txtContrasenia.setEchoChar((char) 0);
        }

        spContrasenia.setForeground(new Color(227, 227, 227));
    }//GEN-LAST:event_txtContraseniaFocusLost

    private void txtCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusGained
        if (txtCorreo.getText().equalsIgnoreCase("Correo electronico")) {
            txtCorreo.setText("");
        }
        spCorreo.setForeground(new Color(0, 153, 255));
    }//GEN-LAST:event_txtCorreoFocusGained

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        if (txtCorreo.getText().isBlank()) {
            txtCorreo.setText("Correo electronico");
        }
        spCorreo.setForeground(new Color(227, 227, 227));
    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtFecha_nacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFecha_nacFocusGained
        if (txtFecha_nac.getText().equalsIgnoreCase("Fecha de nacimiento")) {
            txtFecha_nac.setText("");
        }
        spFecha_nac.setForeground(new Color(0, 153, 255));
    }//GEN-LAST:event_txtFecha_nacFocusGained

    private void txtFecha_nacFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFecha_nacFocusLost
        if (txtFecha_nac.getText().isBlank()) {
            txtFecha_nac.setText("Fecha de nacimiento");
        }
        spFecha_nac.setForeground(new Color(227, 227, 227));
    }//GEN-LAST:event_txtFecha_nacFocusLost

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        comprobarDatos();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilidades.LookVentana.Button btnRegistrar;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lblLogo;
    private utilidades.LookVentana.RoundPanel pnlContenido;
    private javax.swing.JSeparator spContrasenia;
    private javax.swing.JSeparator spCorreo;
    private javax.swing.JSeparator spFecha_nac;
    private javax.swing.JSeparator spUsuario;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFecha_nac;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
