package vista;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import modelo.DAO;

/**
 *
 * @author xDoble_Jx
 */
public class VMain extends javax.swing.JFrame {

    private DAO dao;
    private int posX, posY;
    private boolean iniciarSesion = true;

    /**
     * Creates new form VMain
     */
    public VMain(DAO dao) {
        this.dao = dao;

        initComponents();
        setBackground(new Color(0, 0, 0, 0));

        pRegistrar.setVisible(false);

        pnlArriba.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                posX = e.getX();
                posY = e.getY();
            }
        });

        pnlArriba.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent e) {
                int dx = e.getX() - posX;
                int dy = e.getY() - posY;
                setLocation(getLocation().x + dx, getLocation().y + dy);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new utilidades.LookVentana.RoundPanel();
        pnlArriba = new utilidades.LookVentana.RoundPanel();
        btnSalir = new javax.swing.JButton();
        pInicio = new vista.PInicio(this, dao);
        pRegistrar = new vista.PRegistrar(this, dao);
        btnCambiar = new utilidades.LookVentana.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlFondo.setBackground(new java.awt.Color(21, 21, 21));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlArriba.setBackground(new java.awt.Color(49, 51, 53));

        btnSalir.setBackground(new java.awt.Color(49, 51, 53));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/pantalla/btnCerrar.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlArribaLayout = new javax.swing.GroupLayout(pnlArriba);
        pnlArriba.setLayout(pnlArribaLayout);
        pnlArribaLayout.setHorizontalGroup(
            pnlArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArribaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(14, 14, 14))
        );
        pnlArribaLayout.setVerticalGroup(
            pnlArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArribaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFondo.add(pnlArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 562, -1));
        pnlFondo.add(pInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 53, -1, -1));
        pnlFondo.add(pRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 53, -1, -1));

        btnCambiar.setBackground(new java.awt.Color(227, 227, 227));
        btnCambiar.setForeground(new java.awt.Color(51, 51, 51));
        btnCambiar.setText("Registrar");
        btnCambiar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        if (iniciarSesion) {
            pRegistrar.setVisible(true);
            pInicio.setVisible(false);
            btnCambiar.setText("Registrar");

            iniciarSesion = false;
        } else {
            pRegistrar.setVisible(false);
            pInicio.setVisible(true);
            btnCambiar.setText("Iniciar Sesion");

            iniciarSesion = true;
        }
    }//GEN-LAST:event_btnCambiarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilidades.LookVentana.Button btnCambiar;
    private javax.swing.JButton btnSalir;
    private vista.PInicio pInicio;
    private vista.PRegistrar pRegistrar;
    private utilidades.LookVentana.RoundPanel pnlArriba;
    private utilidades.LookVentana.RoundPanel pnlFondo;
    // End of variables declaration//GEN-END:variables
}
